project:
  type: website
  search: true
  output-dir: docs

website:
  title: "zapad"
  navbar: false
    # search: false
    # left:
    #   - href: index.qmd
    #     text: " "

format:
  html:
    theme: sketchy
    fontsize: 1.4em
    css: styles.css
    toc: false



