project:
  type: website
  search: false
  output-dir: build

website:
  title: "Zapad"
  navbar: false
  favicon: images/favicon.ico

format:
  html:
    theme: sketchy
    fontsize: 1.4em
    toc: false
    include-in-header:
      text: |
        <meta name="robots" content="noindex">
    include-after-body:
      file: analytics.html
