project:
  type: website
  output-dir: _site

website:
  title: "Zapad"
  navbar: false
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: testimonials.qmd
        text: Testimonials
  search: false
  favicon: images/favicon.ico

format:
  html:
    theme: sketchy
    fontsize: 1.4em
    toc: false
    include-in-header:
      text: |
        <meta name="robots" content="noindex">
    include-after-body:
      file: analytics.html

resources:
  - CNAME
