project:
  type: website
  search: true
  output-dir: build

website:
  title: "zapad"
  navbar: false
  favicon: images/favicon.ico

format:
  html:
    theme: sketchy
    fontsize: 1.4em
    css: styles.css
    toc: false
